spring:
  datasource:
    url: jdbc:mysql://localhost:3306/데이터베이스명?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: 여기에_DB_아이디_작성
    password: 여기에_DB_비밀번호_작성
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none 중 택1
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
